# Generated by Django 4.1.7 on 2023-04-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='biography',
            field=models.TextField(default='Tell us about yourself'),
        ),
    ]
