# Generated by Django 4.1.7 on 2023-04-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_profile_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=models.TextField(default='Describe your travel preferences'),
        ),
    ]
