# Generated by Django 4.1.7 on 2023-05-03 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_id_alter_orderitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchase_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 3, 3, 29, 42, 86832, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 5, 3, 3, 30, 9, 892600, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
