# Generated by Django 4.1.7 on 2023-05-08 00:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_purchase_date_order_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='order',
            name='travel_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='travel_time',
            field=models.CharField(default='', max_length=15),
        ),
    ]
